[project]
name = "motion-detection-pipeline"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "imutils>=0.5.4",
    "numpy>=2.3.5",
    "opencv-python>=4.11.0.86",
]
